version: '3'
services:
  selenium-hub:
    image: selenium/hub:3.141.59-neon
    ports:
      - 4444:4444
  chrome:
    depends_on:
      - selenium-hub
    image: selenium/node-chrome:3.141.59-neon
    shm_size: 2g
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
